apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserverv1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webserverv1
    spec:
      containers:
      - name: webserverv1
        image: webserver-image:v1
        ports:
        - containerPort: 80
